[pytest]

# ── Framework ────────────────────────────────────────────────────────────────
api_env             = dev
api_settings_module = config.settings
api_dotenv_file     = .env

# ── Report ───────────────────────────────────────────────────────────────────
addopts             = --api-html-report=reports/{env}/report_{timestamp}.html -v
api_html_theme      = dark
api_html_title      = GoRest API Tests
api_html_header     = GoRest API Test Report

# ── Logging ──────────────────────────────────────────────────────────────────
api_log_level       = DEBUG
log_cli             = true
log_cli_level       = DEBUG
log_cli_format      = %(asctime)s [%(levelname)-8s] %(name)s: %(message)s
log_cli_date_format = %H:%M:%S

# ── Markers ──────────────────────────────────────────────────────────────────
markers =
    smoke: fast sanity checks — run on every commit
    regression: full regression suite
    user: user tests
